module.exports = {
  apps: [
    {
      name: "asifahmed",
      cwd: "/srv/work/plain/asifahmed.tech",
      script: "node_modules/.bin/vinext",
      args: "start --hostname 127.0.0.1 --port 8520",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: "10s",
      kill_timeout: 8000,
      exp_backoff_restart_delay: 200,
      time: true,
      merge_logs: true,
      error_file: "/srv/work/plain/asifahmed.tech/logs/pm2-error.log",
      out_file: "/srv/work/plain/asifahmed.tech/logs/pm2-out.log",
      env: {
        NODE_ENV: "production",
        PORT: "8520",
        HOSTNAME: "127.0.0.1",
        NEXT_PUBLIC_SITE_URL: "https://asifahmed.tech",
        VINEXT_TRUST_PROXY: "1",
        VINEXT_TRUSTED_HOSTS: "asifahmed.tech,www.asifahmed.tech",
        WRANGLER_WRITE_LOGS: "false",
        WRANGLER_LOG_PATH: ".wrangler/wrangler.log",
        MINIFLARE_REGISTRY_PATH: ".wrangler/registry",
      },
    },
  ],
};
